services:
  php:
    build:
      context: ./docker/php
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/html/vendor
      - /var/www/html/var
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
